export let questions = [
	{
		id: 1,
		title: "Que nível de qualidade você está procurando?",
		answers: ["Ótima qualidade", "Boa relação de qualidade e preço", "Não estou interessado em muita qualidade"],
		prices: [14960, 8160, 1360],
		images: ["answer-1-1", "answer-1-2", "answer-1-3"],
		isAnswered: false,
		currentAnswer: undefined,
	},
	{
		id: 2,
		title: "Qual tipo de aplicativo você precisa?",
		answers: ["Aplicativo Android", "Aplicativo iPhone", "Aplicativo Window Phone", "Aplicativo Android e iPhone"],
		prices: [2720, 2720, 2720, 5440],
		images: ["answer-2-1", "answer-2-2", "answer-2-3", "answer-2-4"],
		isAnswered: false,
		currentAnswer: undefined,
	},
	{
		id: 3,
		title: "Qual design você deseja que o seu aplicativo tenha?",
		answers: ["Interface simples", "Interface personalizada", "Interface semelhante à Web", "Sem design"],
		prices: [2720, 8160, 5440, 0],
		images: ["answer-3-1", "answer-3-2", "answer-3-3", "answer-3-4"],
		isAnswered: false,
		currentAnswer: undefined,
	},
	{
		id: 4,
		title: "Qual retorno financeiro você deseja ter?",
		answers: [
			"Aplicativo gratuito com publicidade",
			"Aplicativo pago",
			"Compras dentro do aplicativo",
			"Outros / Ainda não sei",
		],
		prices: [340, 340, 2720, 680],
		images: ["answer-4-1", "answer-4-2", "answer-4-3", "answer-4-4"],
		isAnswered: false,
		currentAnswer: undefined,
	},
	{
		id: 5,
		title: "O seu aplicativo precisa de um sistema de login?",
		answers: ["Sim, com redes sociais e email", "Sim, apenas com email", "Não é necessário login", "Ainda não sei"],
		prices: [2720, 1700, 0, 136],
		images: ["answer-5-1", "answer-5-2", "answer-5-3", "answer-5-4"],
		isAnswered: false,
		currentAnswer: undefined,
	},
	{
		id: 6,
		title: "Seu aplicativo deve ser integrado à um website?",
		answers: ["Sim", "Não", "Ainda não sei"],
		prices: [2720, 0, 1360],
		images: ["answer-6-1", "answer-6-2", "answer-6-3"],
		isAnswered: false,
		currentAnswer: undefined,
	},
	{
		id: 7,
		title: "Os usuários devem ter seu perfil próprio?",
		answers: ["Sim", "Não", "Ainda não sei"],
		prices: [2720, 0, 1360],
		images: ["answer-7-1", "answer-7-2", "answer-7-3"],
		isAnswered: false,
		currentAnswer: undefined,
	},
	{
		id: 8,
		title: "Seu aplicativo necessita de um painel administrativo?",
		answers: ["Sim", "Não", "Ainda não sei"],
		prices: [2720, 0, 1360],
		images: ["answer-8-1", "answer-8-2", "answer-8-3"],
		isAnswered: false,
		currentAnswer: undefined,
	},
	{
		id: 9,
		title: "Quantas línguas você deseja que seu aplicativo tenha?",
		answers: ["Uma única língua", "Bilíngue", "Multilíngue"],
		prices: [0, 1360, 2720],
		images: ["answer-9-1", "answer-9-2", "answer-9-3"],
		isAnswered: false,
		currentAnswer: undefined,
	},
	{
		id: 10,
		title: "Em que estágio se encontra o seu projeto?",
		answers: [
			"É apenas um projeto",
			"Esboço já preparado",
			"Aplicativo em desenvolvimento",
			"Aplicativo já está pronto",
		],
		prices: [0, 0, 0, 0],
		images: ["answer-10-1", "answer-10-2", "answer-10-3", "answer-10-4"],
		isAnswered: false,
		currentAnswer: undefined,
	},
];
